# hello_world
version: '3.7'
services:
  paper:
    build: ./paper
    container_name: paper
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - paper:/opt/minecraft
      - ./paper/data:/opt/data
    ports:
      - 25565:25565
    networks:
      - minecraft
  db:
    image: mariadb
    container_name: paper_db
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: doesntmatter
      MYSQL_USER: paper
      MYSQL_PASSWORD: doesntmattereither
    volumes:
      - db:/var/lib/mysql
    networks:
      - minecraft
volumes:
  paper:
  db:
networks:
  minecraft:
